### ISSUE TITLE
Politico links don't work

### ISSUE THREAD

**Issue by hayleox** [stevenlafl/return-x-link-preview#1]
Really awesome extension, thanks for making it! One issue I've noticed is that this extension doesn't add titles to links to politico.com. The links are completely unmodified; they appear as they would without the extension installed. For examples, see https://twitter.com/politico.

**Comment by stevenlafl** [comment]
Confirmed that's an issue, I'll check this out in a bit to see why.

**Comment by stevenlafl** [comment]
Fixed in [0.0.3](https://github.com/stevenlafl/return-x-link-preview/releases/tag/0.0.3). Should auto update but you can force it by going to about:addons, and doing a "check for updates" 
![image](https://github.com/stevenlafl/return-x-link-preview/assets/2539092/12ef52a5-c24f-4e05-9d38-5d2e9babf715)
